media_social/groups/urls.py
from django.urls import path,include
from groups import views

app_name = 'groups'
urlpatterns = [
    path('',views.ListGroups.as_view(),name='group_list'),
    path('new/',views.CreateGroup.as_view(),name="create_group"),
    path('<slug:slug>/',views.GroupDetails.as_view(),name='group_detail'),
    path('Leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
    path('Join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    ]

media_social/media_social/urls.py
from django.contrib import admin
from django.urls import path,include
from media_social import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls'),name='groups'),
    path('posts/',include('posts.urls'),name='posts'),
]

media_social/posts/urls.py
from django.urls import path,include
from posts import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostListClass.as_view(),name='list_post'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<slug:slug>/',views.UserPostClass.as_view(),name='for_user_post'),
    path('by/<slug:slug>/<int:pk>/',views.PostDetail.as_view(),name='detail_post'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete_post')
    ]

media_social/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from groups.models import Group
from django.contrib.auth import get_user_model
from django.utils.text import slugify
# Create your models here.

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_post')
    created_time = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False,default='',blank=True)
    group = models.ForeignKey(Group,related_name='group_post',null=True,blank=True,on_delete=models.SET_NULL)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html=misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        ordering = ['-created_time']
        unique_together = ['user','message']

media_social/posts/views.py
from django.shortcuts import render
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from posts import models
from posts import forms
from django.contrib.auth import get_user_model
from django.contrib import messages

User = get_user_model()

class PostListClass(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')

class UserPostClass(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.get(username__iexact=self.kwargs.get('username')).prefetch_related('user_post')
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post.user.user_post.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post.user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url =reverse_lazy('posts:list_post')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id =  self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

media_social/posts/templates/posts/_post.html
<!-- inject html -->

<div class="post_media">
  <h3>{{post.message_html|safe}}</h3>
  <div class="media_body">
    <strong>{{post.user.username}}</strong>
    <h5 class="media_heading">
      <a href="{% url 'posts:for_user_post' slug=post.user.username %}">{{post.user.username}}'s Posts</a>
      <time class='time'><a href="{% url 'posts:detail_post' slug=post.user.username pk=post.pk %}"></a></time>
    </h5>
  </div>
  <div class="media_footer">
    {% if user.is_authenticated and post.user == user %}
    <a href="{% url 'posts:delete_post' pk=post.pk %}" class='btn btn-danger'>DELETE</a>
    {% endif %}
  </div>
</div>

media_social/posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
{% block prepost %}{% endblock %}
{% block post_content %}{% endblock %}
{% block post_post %}{% endblock %}
{% endblock %}

media_social/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Confirm delete">
    <a href="{% url 'posts:detail_post' slug=user.username pk=object.pk %}" class='btn btn-default'>Cancel</a>
  </form>
{% endblock %}

media_social/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-md-8">
  {% include 'posts/_post.html' %}
</div>
{% endblock %}

media_social/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block prepost %}
<h4>Create a new Post </h4>
<form class="create" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary" value="Post">
</form>
{% endblock %}

media_social/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% load humanize %}

{% block prepost %}
  {% if user.is_authenticated %}
    <h5>Your groups</h5>
    <ul class="unorder">
      {% for member_group in get_user_groups %}
        <li class='list_groups'><a href="{% url 'groups:group_detail' slug=member_group.group.slug %}">member_group.group.name</a></li>
      {% endfor %}
    </ul>
  {% endif %}
  <h5>All groups</h5>
  <ul class="unorder">
    {% for other_group in get_other_groups %}
    <li class='list_groups'><a href="{% url 'groups:group_detail' slug=other_group.group.slug %}">other_group.group.name</a></li>
    {% endfor %}
  </ul>
{% endblock %}


{% block post_content %}
  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
{% endblock %}

media_social/posts/templates/posts/user_post_list.html
{% exdends 'posts/post_base.html' %}

{% block prepost %}
  <h1>@{{post.user.username}}</h1>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  </div>
{% endblock %}

{% block post_post %}
{% endblock %}