media_social/accounts/urls.py
from django.urls import path,include
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('SignUp/', views.SignUp.as_view(),name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout',kwargs={'next_page':'home'}),
]

media_social/groups/urls.py
from django.urls import path,include
from groups import views

app_name = 'groups'
urlpatterns = [
    path('',views.ListGroups.as_view(),name='group_list'),
    path('new/',views.CreateGroup.as_view(),name="create_group"),
    path('<slug:slug>/',views.GroupDetails.as_view(),name='group_detail'),
    path('Leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
    path('Join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    ]

media_social/media_social/urls.py
from django.contrib import admin
from django.urls import path,include
from media_social import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls'),name='groups'),
    path('posts/',include('posts.urls'),name='posts'),
]

media_social/posts/urls.py
from django.urls import path,include
from posts import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostListClass.as_view(),name='list_post'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<slug:slug>/',views.UserPostClass.as_view(),name='for_user_post'),
    path('by/<slug:slug>/<int:pk>/',views.PostDetail.as_view(),name='detail_post'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete_post')
    ]

media_social/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Social Media</title>
    <!-- bootstrap 4 css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Merienda&family=Neucha&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <!-- static files -->
    <link rel="stylesheet" href="{% static 'master.css' %}">

  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg custom-nav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="https://github.com/sonikaPinto/django">GitHub</a></li>
          <li class="nav-item"><a class="nav-link" href="https://www.linkedin.com/in/sonika-muriel-pinto-031234125/">linkedIn</a></li>
        </ul>
        <ul class="navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'posts:create_post' %}">Post</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:group_list'%}">Groups</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'groups:create_group' %}">Create Group</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
            <li class="nav-item"><a class="nav-link" href='{% url "home" %}'>Welcome {{user.username}}</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="#">Groups</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">
              <span>Login</span>
            </a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">
              <span>SignUp</span>
            </a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

      <div class="container mycontent">
        <div class="row">
          <div class="col-md-12">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>

  </body>
</html>

media_social/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to the page</h1>
{% endblock %}

media_social/templates/thanks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
  <h1>Thanks for visiting! Come back soon :-)</h1>
{% endblock %}