media_social/groups/urls.py
from django.urls import path,include
from groups import views

app_name = 'groups'
urlpatterns = [
    path('',views.ListGroups.as_view(),name='group_list'),
    path('new/',views.CreateGroup.as_view(),name="create_group"),
    path('<slug:slug>/',views.GroupDetails.as_view(),name='group_detail'),
    path('Leave/<slug:slug>',views.LeaveGroup.as_view(),name='leave'),
    path('Join/<slug:slug>',views.JoinGroup.as_view(),name='join'),
    ]

media_social/media_social/urls.py
from django.contrib import admin
from django.urls import path,include
from media_social import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls'),name='groups'),
    path('posts/',include('posts.urls'),name='posts'),
]

media_social/posts/urls.py
from django.urls import path,include
from posts import views

app_name = 'posts'
urlpatterns = [
    path('',views.PostListClass.as_view(),name='list_post'),
    path('new/',views.CreatePost.as_view(),name='create_post'),
    path('by/<slug:slug>/',views.UserPostClass.as_view(),name='for_user_post'),
    path('by/<slug:slug>/<int:pk>/',views.PostDetail.as_view(),name='detail_post'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete_post')
    ]

media_social/groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.urls import reverse
from django.contrib.auth import get_user_model
from django import template
# Create your models here.


User = get_user_model()
#what is this?
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(unique=True,allow_unicode=True,default='',blank=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,blank=True,default='')
    #what is this
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug=slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        ordering =['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE,related_name='membership')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together=('group','user')

media_social/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
# Create your views here.

class CreateGroup(generic.CreateView,LoginRequiredMixin):
    fields = ('name','description')
    model = Group
    success_url=reverse_lazy('groups:group_list')

class ListGroups(generic.ListView):
    model = Group

class GroupDetails(generic.DetailView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:group_detail',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group=get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Warning! Already a member')
        else:
            messages.success(self.request,'you are now a member')
        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:group_detail',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = GroupMember.objects.filter(user=self.request.user,group__slug=self.kwargs.get('slug')).get()
        except:
            messages.warning(self.request,'You arent in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You are removed from the group')
        return super().get(request,*args,**kwargs)

media_social/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
 {% block pregroup %}{% endblock %}
 {% block group %}{% endblock %}
 {% block postgroup %}{% endblock %}
{% endblock %}

media_social/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
  <h1>{{group.name}}</h1>
  <h2> Member Count: {{group.members.count}} </h2>
  {% if user in group.members.all %}
  <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-warning">Leave Group</a>
  {% else %}
  <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-success">Join Group</a>
  {% endif %}
{% endblock %}

{% block group %}
  <div class="col-md-8">
    {% ifequal group.group_post.count 0 %}
      <h3>There are no posts for this group</h3>
    {% else %}
      {% for post in group.group_post.all %}
        {% include 'posts/_post.html' %}
      {% endfor %}
    {% endifequal %}
  </div>
{% endblock %}

media_social/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group %}
<div class="col-md-6">
    <h4>Create your own group!</h4>
    <form class="create-form" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Create">
    </form>
</div>
{% endblock %}

media_social/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
  {% if user.is_authenticated %}
    <h2>Welcome back <a href="#">@{{user.username}}</a></h2>
    <a href="{% url 'groups:create_group' %}" class='btn btn-warning'>Create a new group</a>
  {% endif %}
{% endblock %}


{% block group %}
  <div class="col-md-8">
    {% for group in group_list %}
      <a href="{% url 'groups:group_detail' slug=group.slug %}">{{group.name}}</a>
      <a href="{% url 'groups:group_detail' slug=group.slug %}">{{group.description_html|safe}}</a>
      <div class="count">
        <span class="mem_count">{{group.members.count}}</span> member{{group.members.count|pluralize}}<br>
        <span class="post_count">{{group.group_post.count}}</span> post{{group.group_post.count|pluralize}}
      </div>
    {% endfor %}
  </div>
{% endblock %}